## 基因重组

**未来科技技术共享（合作）协议**

**甲方：**百万立方菌子好逑组

**法定代表人（组长）：**陈照然

**地址：**云南香格里拉（27.801667°N，99.755000°E）

**乙方**：百万立方基因重组

**法定代表人（组长）：**张午阳

**地址：**山东青岛（120°01′57″E，35°50′46″N）

**根据《千万立方合作协议书》等，经双方友好协商，一致达成以下协议，以资共同信守。**

1.  **定义**

除非本合同上下文另有规定，本合同中下列词语含义如下：

1.1 “共享技术”：指本合同第二条所约定的甲方技术和乙方技术的统称。

1.2
“背景知识产权”：指双方在本合同生效日前各自独立开发或合法拥有的，与本合同共享技术相关的知识产权。

1.3
“前景知识产权”：指在技术共享合作期间，基于交换技术由一方或双方共同产生的任何改进、衍生技术成果所对应的知识产权。

2.  **共享技术的内容、范围和要求**

2.1 甲方技术

\- 技术名称：基于CEvNS原理开发的中微子能量立方

\-
交换范围：甲方授予乙方一项非独占的、不可转让的使用许可，允许乙方使用中微子能量立方进行能量供储与动态分配等工作，并允许乙方利用技术进行进一步的立方优化与改造。

\- 许可期限为100年，地域范围为基因重组百万立方及后续扩张范围之内。

2.2 乙方技术

\- 技术名称：通过基因工程改造出的生物史莱姆

\-
交换范围：乙方授予甲方一项非独占的、不可转让的使用许可，允许甲方使用史莱姆进行物资生产、废弃物处理等工作，并允许甲方利用技术进行进一步的基因改造以扩大运用范围。

\- 许可期限为100年，地域范围为菌子好逑组百万立方及后续扩张范围之内。

3.  **技术资料的交付与验收**

3.1交付

时间地点在到达新世界后共同商讨。

3.2技术指导

\-
甲方应在乙方提出合理需求时，提供不超过40人小时的技术指导，以协助乙方理解甲方技术。差旅能源消耗由甲方承担。

\-
乙方应在甲方提出合理需求时，提供不超过40人小时的技术指导，以协助甲方理解乙方技术。差旅能源消耗由乙方承担。

\-
双方在技术资料传输的同时需附有关于技术研发过程的相关资料，以帮助对方理解未来科技的实现路径。

4.  **费用及作价**

4.1 经双方确认，本次技术交换价值对等，互不支付任何费用。

4.2 因履行本合同造成的一切物资消耗和能源消耗，由各方各自承担。

**第五条 其他**

5.1本合同自双方授权代表签字之日起生效，有效期为100年。

5.2
任何对本合同的修改或补充，均须以书面形式作出，并经双方签字盖章后方为有效。

5.3 本合同一式贰份，甲乙双方各执壹份，具有同等法律效力。

5.4 本合同附件为本合同不可分割的组成部分，与本合同具有同等法律效力。

（以下无正文）

**甲方：**百万立方菌子好逑组 **乙方：**百万立方基因重组

**授权代表（签字）：**陈照然 **授权代表（签字）：**张午阳

**日期：**2025年11月30日 **日期：**2025年11月30日
